CREATE TYPE public.account_type AS ENUM ('Client', 'Employee', 'Admin');
ALTER TYPE public.account_type OWNER TO cse340;
CREATE TABLE public.classification (
    classification_id INT GENERATED BY DEFAULT AS IDENTITY,
    classification_name CHARACTER VARYING NOT Null,
    CONSTRAINT classification_pk PRIMARY KEY (classification_id)
);
CREATE TABLE IF NOT EXISTS public.inventory (
    inv_id integer NOT Null GENERATED BY DEFAULT AS IDENTITY,
    inv_make character varying NOT Null,
    inv_model character varying Not Null,
    inv_year character(4) NOT Null,
    inv_description text NOT Null,
    inv_image character varying NOT Null,
    inv_thumbnail character varying NOT Null,
    inv_price numeric(9, 0) NOT Null,
    inv_miles integer NOT Null,
    inv_color character varying NOT Null,
    classification_id integer NOT NULL,
    CONSTRAINT inventory_pkey PRIMARY KEY (inv_id)
);
ALTER TABLE IF EXISTS public.inventory
ADD CONSTRAINT fk_classification FOREIGN KEY (classification_id) REFERENCES public.classification MATCH SIMPLE ON UPDATE CASCADE ON DELETE NO ACTION;
CREATE TABLE IF NOT EXISTS public.account (
    account_id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    account_firstname character varying NOT NULL,
    account_lastname character varying NOT NULL,
    account_email character varying NOT NULL,
    account_password character varying NOT NULL,
    account_type account_type NOT NULL DEFAULT 'Client'::account_type,
    CONSTRAINT account_pkey PRIMARY KEY (account_id)
);
INSERT INTO public.classification (classification_name)
VALUES ('custom'),
    ('Sport'),
    ('SUV'),
    ('Truck'),
    ('Sedan');